services:
  db:
    image: mysql:9.0.1
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: booking_online_tickets
    ports:
      - "2222:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
